#
#  Cleaned up config file
#  @author Diego Calderon
#

#
#   PEOPLE OF THE LAB!
#

p : &people
    current :
        - name : Testing2 Kane
          email : sabenkane@yahoo.com
          position :  Graduate Student
          interest : vertebrate limb development
          pic : /Test/Saben.jpg
        
        - name : Natalie Powers
          email : Pfox83@aol.com
          position :  Graduate Student
          interest :  Identification of WRKY-like sequences in Podophyllum peltatum
          pic : /Test/Natalie.jpg
          
    alumni :
        
            
    



# Default format
permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true

# Some info stuff
title : ACU's Lab
tagline:
author :
  name : Alejandro
  email : calalea@csufresno.edu

# Just used where full domain names are needed like sitemap.txt
production_url : http://zimmer.csufresno.edu/~calalea/

# All Jekyll-Bootstrap specific configurations are namespaced into this hash
JB :
  version : 0.2.13
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive
  categories_path : /categories
  tags_path : /tags
  comments :
    provider :
    disqus :
      short_name : 
  analytics :
    provider : google 
    google : 
        tracking_id : 'UA-29312382-1'
        
        
# Entire site variables!
# Customize your welcome message
welcome : &welcome
    "My name is Alejandro Calderón-Urrea.  I'm a professor of Developmental Biology at California State University, Fresno. The purpose of this site is to introduce you to the different activities that are going on in my research/teaching program. Feel free to send me an e-mail with comments and suggestions."
    
test : *welcome

menu :
    research :
    people : *people
    publications :
    positions :
    courses :
    links :
    contact :

